version: 2

updates:
  - package-ecosystem: 'docker'
    directory: '/server'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/client'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'gradle'
    directory: '/app'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
