tasks:
  - name: Run PostgreSQL Database
    command: docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres

  - name: Restore Environment Variables
    command: |
      if [ -f .env ]; then
        echo "Found .env in workspace"
      else
        if [ -z "${DOTENV}" ]; then
          echo "Setting example .env"
          cp .env.gitpod .env
        else
          echo "Restoring .env from Gitpod"
          echo "${DOTENV}" | base64 -d > .env
        fi
      fi

  - name: Install Project Dependencies
    command: |
      npx playwright install-deps
      pnpm install

ports:
  # PostgreSQL
  - port: 5432
    visibility: private

  # Client
  - port: 3100
    visibility: public
    onOpen: ignore

  # Client
  - port: 3000
    visibility: public
    onOpen: open-browser
