tasks:
  - name: Run PostgreSQL Database
    command: docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres

  - name: Generate Environment Variables
    command: |
      if [ -f .env ]; then
        echo "Found .env in workspace, skipping generation"
      else
        pnpm generate-env
      fi

  - name: Install Project Dependencies
    command: |
      npx playwright install-deps
      pnpm install

ports:
  # PostgreSQL
  - port: 5432
    visibility: private

  # Client
  - port: 3100
    visibility: public
    onOpen: ignore

  # Client
  - port: 3000
    visibility: public
    onOpen: open-browser
