tasks:
  - name: Restore .env file, or create a new one
    command: |
      if [ -f .env ]; then
        echo "Found .env in workspace"
      else
        if [ -z "${DOTENV}" ]; then
          echo "Setting example .env"
          cp .env.gitpod .env
        else
          echo "Restoring .env from Gitpod"
          echo "${DOTENV}" | base64 -d > .env
        fi
      fi

  - name: Set up dependencies, and run the development server
    init: pnpm install
    command: pnpm dev

ports:
  # PostgreSQL
  - port: 5432
    visibility: private

  # Client
  - port: 3100
    visibility: public
    onOpen: ignore

  # Client
  - port: 3000
    visibility: public
    onOpen: open-browser
