version: '3'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    volumes:
      - ./scripts/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
