version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - ./scripts/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
      - pgdata:/var/lib/postgresql/data

  # Development
  # app:
  #   build: .
  #   container_name: app
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3000:3000'
  #     - '3100:3100'
  #   env_file: .env
  #   environment:
  #     NODE_ENV: development
  #     POSTGRES_HOST: postgres

  # Production
  # app:
  #   image: amruthpillai/reactive-resume
  #   container_name: app
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3000:3000'
  #     - '3100:3100'
  #   env_file: .env
  #   environment:
  #     NODE_ENV: production
  #     POSTGRES_HOST: postgres

volumes:
  pgdata:
