version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./scripts/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
      - pgdata:/var/lib/postgresql/data

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: server
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 3100:3100

  client:
    image: amruthpillai/reactive-resume:client-latest
    container_name: client
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - server

volumes:
  pgdata:
