name: Build and Push to Docker Hub

on:
  push:
    branches:
      - 'v3'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.0

      - name: Get Short Commit SHA
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: $GITHUB_REPOSITORY_OWNER
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Server Docker Image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          file: server/Dockerfile
          tags: |
            amruthpillai/reactive-resume:server-latest
            amruthpillai/reactive-resume:server-${{ steps.slug.outputs.sha8 }}
            ghcr.io/amruthpillai/reactive-resume:server-latest
            ghcr.io/amruthpillai/reactive-resume:server-${{ steps.slug.outputs.sha8 }}

      - name: Build and Push Client Docker Image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          file: client/Dockerfile
          tags: |
            amruthpillai/reactive-resume:client-latest
            amruthpillai/reactive-resume:client-${{ steps.slug.outputs.sha8 }}
            ghcr.io/amruthpillai/reactive-resume:client-latest
            ghcr.io/amruthpillai/reactive-resume:client-${{ steps.slug.outputs.sha8 }}
